//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.0.0 (NJsonSchema v11.6.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Service {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    list(): Promise<BLFParameter[]> {
        let url_ = this.baseUrl + "/api/blfParameter/list";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processList(_response);
        });
    }

    protected processList(response: Response): Promise<BLFParameter[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(BLFParameter.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BLFParameter[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    detail(body: GetBLFParameterRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/blfParameter/detail";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDetail(_response);
        });
    }

    protected processDetail(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    create(body: BLFParameter | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/blfParameter/create";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    update(body: BLFParameter | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/blfParameter/update";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdate(_response);
        });
    }

    protected processUpdate(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    delete(body: string[] | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/blfParameter/delete";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDelete(_response);
        });
    }

    protected processDelete(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    convertToPMCDeliveryReviewList(body: PMCRequestDto | undefined): Promise<PMCDeliveryReviewListApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/ConvertToPMCDeliveryReviewList";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processConvertToPMCDeliveryReviewList(_response);
        });
    }

    protected processConvertToPMCDeliveryReviewList(response: Response): Promise<PMCDeliveryReviewListApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = PMCDeliveryReviewListApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PMCDeliveryReviewListApiResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    productListInfo(body: PMCRequestDto | undefined): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/ProductListInfo";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processProductListInfo(_response);
        });
    }

    protected processProductListInfo(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    productDataAssemblyList(body: PMCRequestDto | undefined): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/ProductDataAssemblyList";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processProductDataAssemblyList(_response);
        });
    }

    protected processProductDataAssemblyList(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    checkAssemblyList(body: PMCRequestDto | undefined): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/CheckAssemblyList";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCheckAssemblyList(_response);
        });
    }

    protected processCheckAssemblyList(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    pMCDeliveryReviewList(body: PMCRequestDto | undefined): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/PMCDeliveryReviewList";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPMCDeliveryReviewList(_response);
        });
    }

    protected processPMCDeliveryReviewList(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    addPMCDeliveryReview(body: PMCDeliveryReview | undefined): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/AddPMCDeliveryReview";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAddPMCDeliveryReview(_response);
        });
    }

    protected processAddPMCDeliveryReview(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @return OK
     */
    addPMCSalesControlList(): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/AddPMCSalesControlList";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAddPMCSalesControlList(_response);
        });
    }

    protected processAddPMCSalesControlList(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    getPMCSalesControlList(body: PMCRequestDto | undefined): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/GetPMCSalesControlList";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetPMCSalesControlList(_response);
        });
    }

    protected processGetPMCSalesControlList(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    getPMCProductData(body: PMCRequestDto | undefined): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/GetPMCProductData";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetPMCProductData(_response);
        });
    }

    protected processGetPMCProductData(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    schedulingAnalysisList(body: PMCRequestDto | undefined): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/SchedulingAnalysisList";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSchedulingAnalysisList(_response);
        });
    }

    protected processSchedulingAnalysisList(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @return OK
     */
    getPMCWorkOrderList(): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/GetPMCWorkOrderList";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetPMCWorkOrderList(_response);
        });
    }

    protected processGetPMCWorkOrderList(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    updatePMCWorkOrder(body: PMCWorkOrder | undefined): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/UpdatePMCWorkOrder";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdatePMCWorkOrder(_response);
        });
    }

    protected processUpdatePMCWorkOrder(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    addPMCWorkOrder(body: PMCWorkOrder | undefined): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/AddPMCWorkOrder";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAddPMCWorkOrder(_response);
        });
    }

    protected processAddPMCWorkOrder(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    addPMCWorkOrderByRequest(body: PMCRequestDto | undefined): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/AddPMCWorkOrderByRequest";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAddPMCWorkOrderByRequest(_response);
        });
    }

    protected processAddPMCWorkOrderByRequest(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    addOrUpdateWorkOrderSalesControlList(body: WorkOrderSalesControl[] | undefined): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/AddOrUpdateWorkOrderSalesControlList";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAddOrUpdateWorkOrderSalesControlList(_response);
        });
    }

    protected processAddOrUpdateWorkOrderSalesControlList(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    getWorkOrderSalesControlList(body: PMCRequestDto | undefined): Promise<ObjectApiResponse> {
        let url_ = this.baseUrl + "/api/PMC/GetWorkOrderSalesControlList";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetWorkOrderSalesControlList(_response);
        });
    }

    protected processGetWorkOrderSalesControlList(response: Response): Promise<ObjectApiResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ObjectApiResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ObjectApiResponse>(null as any);
    }

    /**
     * @param redirectUri (optional) 
     * @param state (optional) 
     * @return OK
     */
    authorizeUrl(redirectUri: string | undefined, state: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Wechat/authorize-url?";
        if (redirectUri === null)
            throw new globalThis.Error("The parameter 'redirectUri' cannot be null.");
        else if (redirectUri !== undefined)
            url_ += "redirectUri=" + encodeURIComponent("" + redirectUri) + "&";
        if (state === null)
            throw new globalThis.Error("The parameter 'state' cannot be null.");
        else if (state !== undefined)
            url_ += "state=" + encodeURIComponent("" + state) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAuthorizeUrl(_response);
        });
    }

    protected processAuthorizeUrl(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param code (optional) 
     * @param state (optional) 
     * @return OK
     */
    callback(code: string | undefined, state: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Wechat/callback?";
        if (code === null)
            throw new globalThis.Error("The parameter 'code' cannot be null.");
        else if (code !== undefined)
            url_ += "code=" + encodeURIComponent("" + code) + "&";
        if (state === null)
            throw new globalThis.Error("The parameter 'state' cannot be null.");
        else if (state !== undefined)
            url_ += "state=" + encodeURIComponent("" + state) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCallback(_response);
        });
    }

    protected processCallback(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    user(userId: string): Promise<void> {
        let url_ = this.baseUrl + "/api/Wechat/user/{userId}";
        if (userId === undefined || userId === null)
            throw new globalThis.Error("The parameter 'userId' must be defined.");
        url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUser(_response);
        });
    }

    protected processUser(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    users(body: DepartmentRequestDto | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/WechatWork/users";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUsers(_response);
        });
    }

    protected processUsers(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    departments(): Promise<void> {
        let url_ = this.baseUrl + "/api/WechatWork/departments";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDepartments(_response);
        });
    }

    protected processDepartments(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    send(body: SendMessageDto | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/WechatWork/send";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSend(_response);
        });
    }

    protected processSend(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    sendCardMessage(body: SendMessageDto | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/WechatWork/sendCardMessage";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSendCardMessage(_response);
        });
    }

    protected processSendCardMessage(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    createSmartSheet(body: CreateSmartSheetDto | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/WechatWork/createSmartSheet";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateSmartSheet(_response);
        });
    }

    protected processCreateSmartSheet(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param docId (optional) 
     * @param sheetId (optional) 
     * @return OK
     */
    addSmartSheetRecord(docId: string | undefined, sheetId: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/WechatWork/addSmartSheetRecord?";
        if (docId === null)
            throw new globalThis.Error("The parameter 'docId' cannot be null.");
        else if (docId !== undefined)
            url_ += "docId=" + encodeURIComponent("" + docId) + "&";
        if (sheetId === null)
            throw new globalThis.Error("The parameter 'sheetId' cannot be null.");
        else if (sheetId !== undefined)
            url_ += "sheetId=" + encodeURIComponent("" + sheetId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAddSmartSheetRecord(_response);
        });
    }

    protected processAddSmartSheetRecord(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param docId (optional) 
     * @param sheetId (optional) 
     * @return OK
     */
    getSmartSheetRecord(docId: string | undefined, sheetId: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/WechatWork/getSmartSheetRecord?";
        if (docId === null)
            throw new globalThis.Error("The parameter 'docId' cannot be null.");
        else if (docId !== undefined)
            url_ += "docId=" + encodeURIComponent("" + docId) + "&";
        if (sheetId === null)
            throw new globalThis.Error("The parameter 'sheetId' cannot be null.");
        else if (sheetId !== undefined)
            url_ += "sheetId=" + encodeURIComponent("" + sheetId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetSmartSheetRecord(_response);
        });
    }

    protected processGetSmartSheetRecord(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    createSmartSheetAndNotify(body: CreateAndNotifyDto | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/WechatWork/createSmartSheetAndNotify";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateSmartSheetAndNotify(_response);
        });
    }

    protected processCreateSmartSheetAndNotify(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param url (optional) 
     * @return OK
     */
    jssdkConfig(url: string | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/WechatWork/jssdk-config?";
        if (url === null)
            throw new globalThis.Error("The parameter 'url' cannot be null.");
        else if (url !== undefined)
            url_ += "url=" + encodeURIComponent("" + url) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processJssdkConfig(_response);
        });
    }

    protected processJssdkConfig(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class BLFParameter implements IBLFParameter {
    id?: string;
    workOrderNumber?: string | undefined;
    bLFNumber?: string | undefined;
    coilResistance?: string | undefined;
    insulationResistance?: string | undefined;
    insulationStrength?: string | undefined;
    withstandVoltageStrength?: string | undefined;
    internalLeakage?: string | undefined;
    externalLeakage?: string | undefined;
    currentFlowRateCurve?: CurrentFlowRate[] | undefined;
    startingCurrent?: string | undefined;
    maximumFlowRate?: string | undefined;
    hysteresis?: string | undefined;
    pressureFlowRateCurve?: PressureFlowRate[] | undefined;
    closedLoopFluctuation1?: string | undefined;
    closedLoopFluctuation2?: string | undefined;
    closedLoopFluctuation3?: string | undefined;
    closedLoopFluctuation4?: string | undefined;
    createDate?: Date;
    modifyDate?: Date;

    constructor(data?: IBLFParameter) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.workOrderNumber = _data["WorkOrderNumber"];
            this.bLFNumber = _data["BLFNumber"];
            this.coilResistance = _data["CoilResistance"];
            this.insulationResistance = _data["InsulationResistance"];
            this.insulationStrength = _data["InsulationStrength"];
            this.withstandVoltageStrength = _data["WithstandVoltageStrength"];
            this.internalLeakage = _data["InternalLeakage"];
            this.externalLeakage = _data["ExternalLeakage"];
            if (Array.isArray(_data["CurrentFlowRateCurve"])) {
                this.currentFlowRateCurve = [] as any;
                for (let item of _data["CurrentFlowRateCurve"])
                    this.currentFlowRateCurve!.push(CurrentFlowRate.fromJS(item));
            }
            this.startingCurrent = _data["StartingCurrent"];
            this.maximumFlowRate = _data["MaximumFlowRate"];
            this.hysteresis = _data["Hysteresis"];
            if (Array.isArray(_data["PressureFlowRateCurve"])) {
                this.pressureFlowRateCurve = [] as any;
                for (let item of _data["PressureFlowRateCurve"])
                    this.pressureFlowRateCurve!.push(PressureFlowRate.fromJS(item));
            }
            this.closedLoopFluctuation1 = _data["ClosedLoopFluctuation1"];
            this.closedLoopFluctuation2 = _data["ClosedLoopFluctuation2"];
            this.closedLoopFluctuation3 = _data["ClosedLoopFluctuation3"];
            this.closedLoopFluctuation4 = _data["ClosedLoopFluctuation4"];
            this.createDate = _data["CreateDate"] ? new Date(_data["CreateDate"].toString()) : undefined as any;
            this.modifyDate = _data["ModifyDate"] ? new Date(_data["ModifyDate"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): BLFParameter {
        data = typeof data === 'object' ? data : {};
        let result = new BLFParameter();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["WorkOrderNumber"] = this.workOrderNumber;
        data["BLFNumber"] = this.bLFNumber;
        data["CoilResistance"] = this.coilResistance;
        data["InsulationResistance"] = this.insulationResistance;
        data["InsulationStrength"] = this.insulationStrength;
        data["WithstandVoltageStrength"] = this.withstandVoltageStrength;
        data["InternalLeakage"] = this.internalLeakage;
        data["ExternalLeakage"] = this.externalLeakage;
        if (Array.isArray(this.currentFlowRateCurve)) {
            data["CurrentFlowRateCurve"] = [];
            for (let item of this.currentFlowRateCurve)
                data["CurrentFlowRateCurve"].push(item ? item.toJSON() : undefined as any);
        }
        data["StartingCurrent"] = this.startingCurrent;
        data["MaximumFlowRate"] = this.maximumFlowRate;
        data["Hysteresis"] = this.hysteresis;
        if (Array.isArray(this.pressureFlowRateCurve)) {
            data["PressureFlowRateCurve"] = [];
            for (let item of this.pressureFlowRateCurve)
                data["PressureFlowRateCurve"].push(item ? item.toJSON() : undefined as any);
        }
        data["ClosedLoopFluctuation1"] = this.closedLoopFluctuation1;
        data["ClosedLoopFluctuation2"] = this.closedLoopFluctuation2;
        data["ClosedLoopFluctuation3"] = this.closedLoopFluctuation3;
        data["ClosedLoopFluctuation4"] = this.closedLoopFluctuation4;
        data["CreateDate"] = this.createDate ? this.createDate.toISOString() : undefined as any;
        data["ModifyDate"] = this.modifyDate ? this.modifyDate.toISOString() : undefined as any;
        return data;
    }
}

export interface IBLFParameter {
    id?: string;
    workOrderNumber?: string | undefined;
    bLFNumber?: string | undefined;
    coilResistance?: string | undefined;
    insulationResistance?: string | undefined;
    insulationStrength?: string | undefined;
    withstandVoltageStrength?: string | undefined;
    internalLeakage?: string | undefined;
    externalLeakage?: string | undefined;
    currentFlowRateCurve?: CurrentFlowRate[] | undefined;
    startingCurrent?: string | undefined;
    maximumFlowRate?: string | undefined;
    hysteresis?: string | undefined;
    pressureFlowRateCurve?: PressureFlowRate[] | undefined;
    closedLoopFluctuation1?: string | undefined;
    closedLoopFluctuation2?: string | undefined;
    closedLoopFluctuation3?: string | undefined;
    closedLoopFluctuation4?: string | undefined;
    createDate?: Date;
    modifyDate?: Date;
}

export class CreateAndNotifyDto implements ICreateAndNotifyDto {
    title?: string | undefined;
    adminUserIds?: string[] | undefined;
    noticeUsers?: string[] | undefined;

    constructor(data?: ICreateAndNotifyDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["Title"];
            if (Array.isArray(_data["AdminUserIds"])) {
                this.adminUserIds = [] as any;
                for (let item of _data["AdminUserIds"])
                    this.adminUserIds!.push(item);
            }
            if (Array.isArray(_data["NoticeUsers"])) {
                this.noticeUsers = [] as any;
                for (let item of _data["NoticeUsers"])
                    this.noticeUsers!.push(item);
            }
        }
    }

    static fromJS(data: any): CreateAndNotifyDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreateAndNotifyDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Title"] = this.title;
        if (Array.isArray(this.adminUserIds)) {
            data["AdminUserIds"] = [];
            for (let item of this.adminUserIds)
                data["AdminUserIds"].push(item);
        }
        if (Array.isArray(this.noticeUsers)) {
            data["NoticeUsers"] = [];
            for (let item of this.noticeUsers)
                data["NoticeUsers"].push(item);
        }
        return data;
    }
}

export interface ICreateAndNotifyDto {
    title?: string | undefined;
    adminUserIds?: string[] | undefined;
    noticeUsers?: string[] | undefined;
}

export class CreateSmartSheetDto implements ICreateSmartSheetDto {
    title?: string | undefined;
    adminUserIds?: string[] | undefined;

    constructor(data?: ICreateSmartSheetDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["Title"];
            if (Array.isArray(_data["AdminUserIds"])) {
                this.adminUserIds = [] as any;
                for (let item of _data["AdminUserIds"])
                    this.adminUserIds!.push(item);
            }
        }
    }

    static fromJS(data: any): CreateSmartSheetDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreateSmartSheetDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Title"] = this.title;
        if (Array.isArray(this.adminUserIds)) {
            data["AdminUserIds"] = [];
            for (let item of this.adminUserIds)
                data["AdminUserIds"].push(item);
        }
        return data;
    }
}

export interface ICreateSmartSheetDto {
    title?: string | undefined;
    adminUserIds?: string[] | undefined;
}

export class CurrentFlowRate implements ICurrentFlowRate {
    id?: string;
    current?: number;
    flowRate?: number;

    constructor(data?: ICurrentFlowRate) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.current = _data["Current"];
            this.flowRate = _data["FlowRate"];
        }
    }

    static fromJS(data: any): CurrentFlowRate {
        data = typeof data === 'object' ? data : {};
        let result = new CurrentFlowRate();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["Current"] = this.current;
        data["FlowRate"] = this.flowRate;
        return data;
    }
}

export interface ICurrentFlowRate {
    id?: string;
    current?: number;
    flowRate?: number;
}

export class DepartmentRequestDto implements IDepartmentRequestDto {
    departmentId?: number;

    constructor(data?: IDepartmentRequestDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.departmentId = _data["DepartmentId"];
        }
    }

    static fromJS(data: any): DepartmentRequestDto {
        data = typeof data === 'object' ? data : {};
        let result = new DepartmentRequestDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["DepartmentId"] = this.departmentId;
        return data;
    }
}

export interface IDepartmentRequestDto {
    departmentId?: number;
}

export class GetBLFParameterRequest implements IGetBLFParameterRequest {
    number!: string | undefined;

    constructor(data?: IGetBLFParameterRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.number = _data["Number"];
        }
    }

    static fromJS(data: any): GetBLFParameterRequest {
        data = typeof data === 'object' ? data : {};
        let result = new GetBLFParameterRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Number"] = this.number;
        return data;
    }
}

export interface IGetBLFParameterRequest {
    number: string | undefined;
}

export class ObjectApiResponse implements IObjectApiResponse {
    success?: boolean;
    message?: string | undefined;
    data?: any | undefined;
    timestamp?: Date;

    constructor(data?: IObjectApiResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["Success"];
            this.message = _data["Message"];
            this.data = _data["Data"];
            this.timestamp = _data["Timestamp"] ? new Date(_data["Timestamp"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): ObjectApiResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ObjectApiResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Success"] = this.success;
        data["Message"] = this.message;
        data["Data"] = this.data;
        data["Timestamp"] = this.timestamp ? this.timestamp.toISOString() : undefined as any;
        return data;
    }
}

export interface IObjectApiResponse {
    success?: boolean;
    message?: string | undefined;
    data?: any | undefined;
    timestamp?: Date;
}

export class PMCDeliveryReview implements IPMCDeliveryReview {
    编号?: string | undefined;
    用户编号?: string | undefined;
    用户铭?: string | undefined;
    修改状态?: string | undefined;
    创建时间?: string | undefined;
    锁定用户?: string | undefined;
    审核过程?: string | undefined;
    打印?: string | undefined;
    合同号?: string | undefined;
    排产编号?: string | undefined;
    数量?: string | undefined;
    货号?: string | undefined;
    中文品名?: string | undefined;
    中文规格?: string | undefined;
    分析单号?: string | undefined;
    来源编号?: string | undefined;
    来源?: string | undefined;
    工单单号?: string | undefined;
    线圈货号?: string | undefined;
    电压?: string | undefined;
    交货日期?: string | undefined;
    排产用户?: string | undefined;
    状态?: string | undefined;
    物料货号?: string | undefined;
    备注?: string | undefined;

    constructor(data?: IPMCDeliveryReview) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.编号 = _data["编号"];
            this.用户编号 = _data["用户编号"];
            this.用户铭 = _data["用户铭"];
            this.修改状态 = _data["修改状态"];
            this.创建时间 = _data["创建时间"];
            this.锁定用户 = _data["锁定用户"];
            this.审核过程 = _data["审核过程"];
            this.打印 = _data["打印"];
            this.合同号 = _data["合同号"];
            this.排产编号 = _data["排产编号"];
            this.数量 = _data["数量"];
            this.货号 = _data["货号"];
            this.中文品名 = _data["中文品名"];
            this.中文规格 = _data["中文规格"];
            this.分析单号 = _data["分析单号"];
            this.来源编号 = _data["来源编号"];
            this.来源 = _data["来源"];
            this.工单单号 = _data["工单单号"];
            this.线圈货号 = _data["线圈货号"];
            this.电压 = _data["电压"];
            this.交货日期 = _data["交货日期"];
            this.排产用户 = _data["排产用户"];
            this.状态 = _data["状态"];
            this.物料货号 = _data["物料货号"];
            this.备注 = _data["备注"];
        }
    }

    static fromJS(data: any): PMCDeliveryReview {
        data = typeof data === 'object' ? data : {};
        let result = new PMCDeliveryReview();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["编号"] = this.编号;
        data["用户编号"] = this.用户编号;
        data["用户铭"] = this.用户铭;
        data["修改状态"] = this.修改状态;
        data["创建时间"] = this.创建时间;
        data["锁定用户"] = this.锁定用户;
        data["审核过程"] = this.审核过程;
        data["打印"] = this.打印;
        data["合同号"] = this.合同号;
        data["排产编号"] = this.排产编号;
        data["数量"] = this.数量;
        data["货号"] = this.货号;
        data["中文品名"] = this.中文品名;
        data["中文规格"] = this.中文规格;
        data["分析单号"] = this.分析单号;
        data["来源编号"] = this.来源编号;
        data["来源"] = this.来源;
        data["工单单号"] = this.工单单号;
        data["线圈货号"] = this.线圈货号;
        data["电压"] = this.电压;
        data["交货日期"] = this.交货日期;
        data["排产用户"] = this.排产用户;
        data["状态"] = this.状态;
        data["物料货号"] = this.物料货号;
        data["备注"] = this.备注;
        return data;
    }
}

export interface IPMCDeliveryReview {
    编号?: string | undefined;
    用户编号?: string | undefined;
    用户铭?: string | undefined;
    修改状态?: string | undefined;
    创建时间?: string | undefined;
    锁定用户?: string | undefined;
    审核过程?: string | undefined;
    打印?: string | undefined;
    合同号?: string | undefined;
    排产编号?: string | undefined;
    数量?: string | undefined;
    货号?: string | undefined;
    中文品名?: string | undefined;
    中文规格?: string | undefined;
    分析单号?: string | undefined;
    来源编号?: string | undefined;
    来源?: string | undefined;
    工单单号?: string | undefined;
    线圈货号?: string | undefined;
    电压?: string | undefined;
    交货日期?: string | undefined;
    排产用户?: string | undefined;
    状态?: string | undefined;
    物料货号?: string | undefined;
    备注?: string | undefined;
}

export class PMCDeliveryReviewListApiResponse implements IPMCDeliveryReviewListApiResponse {
    success?: boolean;
    message?: string | undefined;
    data?: PMCDeliveryReview[] | undefined;
    timestamp?: Date;

    constructor(data?: IPMCDeliveryReviewListApiResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.success = _data["Success"];
            this.message = _data["Message"];
            if (Array.isArray(_data["Data"])) {
                this.data = [] as any;
                for (let item of _data["Data"])
                    this.data!.push(PMCDeliveryReview.fromJS(item));
            }
            this.timestamp = _data["Timestamp"] ? new Date(_data["Timestamp"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): PMCDeliveryReviewListApiResponse {
        data = typeof data === 'object' ? data : {};
        let result = new PMCDeliveryReviewListApiResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Success"] = this.success;
        data["Message"] = this.message;
        if (Array.isArray(this.data)) {
            data["Data"] = [];
            for (let item of this.data)
                data["Data"].push(item ? item.toJSON() : undefined as any);
        }
        data["Timestamp"] = this.timestamp ? this.timestamp.toISOString() : undefined as any;
        return data;
    }
}

export interface IPMCDeliveryReviewListApiResponse {
    success?: boolean;
    message?: string | undefined;
    data?: PMCDeliveryReview[] | undefined;
    timestamp?: Date;
}

export class PMCRequestDto implements IPMCRequestDto {
    合同号?: string | undefined;
    排产编号?: string | undefined;
    分析单号?: string | undefined;
    货号?: string | undefined;
    线圈货号?: string | undefined;
    补充数据?: string | undefined;

    constructor(data?: IPMCRequestDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.合同号 = _data["合同号"];
            this.排产编号 = _data["排产编号"];
            this.分析单号 = _data["分析单号"];
            this.货号 = _data["货号"];
            this.线圈货号 = _data["线圈货号"];
            this.补充数据 = _data["补充数据"];
        }
    }

    static fromJS(data: any): PMCRequestDto {
        data = typeof data === 'object' ? data : {};
        let result = new PMCRequestDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["合同号"] = this.合同号;
        data["排产编号"] = this.排产编号;
        data["分析单号"] = this.分析单号;
        data["货号"] = this.货号;
        data["线圈货号"] = this.线圈货号;
        data["补充数据"] = this.补充数据;
        return data;
    }
}

export interface IPMCRequestDto {
    合同号?: string | undefined;
    排产编号?: string | undefined;
    分析单号?: string | undefined;
    货号?: string | undefined;
    线圈货号?: string | undefined;
    补充数据?: string | undefined;
}

export class PMCWorkOrder implements IPMCWorkOrder {
    编号?: string | undefined;
    用户编号?: string | undefined;
    用户铭?: string | undefined;
    修改状态?: string | undefined;
    创建时间?: string | undefined;
    锁定用户?: string | undefined;
    审核过程?: string | undefined;
    打印?: string | undefined;
    计划开工日?: string | undefined;
    计划完工日?: string | undefined;
    状态?: string | undefined;
    工单单号?: string | undefined;
    物料齐套?: string | undefined;
    物料配料?: string | undefined;
    上线情况?: string | undefined;
    生产单位?: string | undefined;
    成品编号?: string | undefined;
    成品品名?: string | undefined;
    规格?: string | undefined;
    需求数量?: string | undefined;
    入库数量?: string | undefined;
    未入库数量?: string | undefined;
    报工工艺?: string | undefined;
    报工数?: string | undefined;
    报工日期?: string | undefined;
    制单?: string | undefined;
    订单编号?: string | undefined;

    constructor(data?: IPMCWorkOrder) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.编号 = _data["编号"];
            this.用户编号 = _data["用户编号"];
            this.用户铭 = _data["用户铭"];
            this.修改状态 = _data["修改状态"];
            this.创建时间 = _data["创建时间"];
            this.锁定用户 = _data["锁定用户"];
            this.审核过程 = _data["审核过程"];
            this.打印 = _data["打印"];
            this.计划开工日 = _data["计划开工日"];
            this.计划完工日 = _data["计划完工日"];
            this.状态 = _data["状态"];
            this.工单单号 = _data["工单单号"];
            this.物料齐套 = _data["物料齐套"];
            this.物料配料 = _data["物料配料"];
            this.上线情况 = _data["上线情况"];
            this.生产单位 = _data["生产单位"];
            this.成品编号 = _data["成品编号"];
            this.成品品名 = _data["成品品名"];
            this.规格 = _data["规格"];
            this.需求数量 = _data["需求数量"];
            this.入库数量 = _data["入库数量"];
            this.未入库数量 = _data["未入库数量"];
            this.报工工艺 = _data["报工工艺"];
            this.报工数 = _data["报工数"];
            this.报工日期 = _data["报工日期"];
            this.制单 = _data["制单"];
            this.订单编号 = _data["订单编号"];
        }
    }

    static fromJS(data: any): PMCWorkOrder {
        data = typeof data === 'object' ? data : {};
        let result = new PMCWorkOrder();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["编号"] = this.编号;
        data["用户编号"] = this.用户编号;
        data["用户铭"] = this.用户铭;
        data["修改状态"] = this.修改状态;
        data["创建时间"] = this.创建时间;
        data["锁定用户"] = this.锁定用户;
        data["审核过程"] = this.审核过程;
        data["打印"] = this.打印;
        data["计划开工日"] = this.计划开工日;
        data["计划完工日"] = this.计划完工日;
        data["状态"] = this.状态;
        data["工单单号"] = this.工单单号;
        data["物料齐套"] = this.物料齐套;
        data["物料配料"] = this.物料配料;
        data["上线情况"] = this.上线情况;
        data["生产单位"] = this.生产单位;
        data["成品编号"] = this.成品编号;
        data["成品品名"] = this.成品品名;
        data["规格"] = this.规格;
        data["需求数量"] = this.需求数量;
        data["入库数量"] = this.入库数量;
        data["未入库数量"] = this.未入库数量;
        data["报工工艺"] = this.报工工艺;
        data["报工数"] = this.报工数;
        data["报工日期"] = this.报工日期;
        data["制单"] = this.制单;
        data["订单编号"] = this.订单编号;
        return data;
    }
}

export interface IPMCWorkOrder {
    编号?: string | undefined;
    用户编号?: string | undefined;
    用户铭?: string | undefined;
    修改状态?: string | undefined;
    创建时间?: string | undefined;
    锁定用户?: string | undefined;
    审核过程?: string | undefined;
    打印?: string | undefined;
    计划开工日?: string | undefined;
    计划完工日?: string | undefined;
    状态?: string | undefined;
    工单单号?: string | undefined;
    物料齐套?: string | undefined;
    物料配料?: string | undefined;
    上线情况?: string | undefined;
    生产单位?: string | undefined;
    成品编号?: string | undefined;
    成品品名?: string | undefined;
    规格?: string | undefined;
    需求数量?: string | undefined;
    入库数量?: string | undefined;
    未入库数量?: string | undefined;
    报工工艺?: string | undefined;
    报工数?: string | undefined;
    报工日期?: string | undefined;
    制单?: string | undefined;
    订单编号?: string | undefined;
}

export class PressureFlowRate implements IPressureFlowRate {
    id?: string;
    pressure?: number;
    flowRate?: number;

    constructor(data?: IPressureFlowRate) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.pressure = _data["Pressure"];
            this.flowRate = _data["FlowRate"];
        }
    }

    static fromJS(data: any): PressureFlowRate {
        data = typeof data === 'object' ? data : {};
        let result = new PressureFlowRate();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["Pressure"] = this.pressure;
        data["FlowRate"] = this.flowRate;
        return data;
    }
}

export interface IPressureFlowRate {
    id?: string;
    pressure?: number;
    flowRate?: number;
}

export class SendMessageDto implements ISendMessageDto {
    users?: string[] | undefined;
    content?: string | undefined;
    title?: string | undefined;
    description?: string | undefined;
    url?: string | undefined;
    msgType?: WechatWorkMessageType;

    constructor(data?: ISendMessageDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["Users"])) {
                this.users = [] as any;
                for (let item of _data["Users"])
                    this.users!.push(item);
            }
            this.content = _data["Content"];
            this.title = _data["Title"];
            this.description = _data["Description"];
            this.url = _data["Url"];
            this.msgType = _data["MsgType"];
        }
    }

    static fromJS(data: any): SendMessageDto {
        data = typeof data === 'object' ? data : {};
        let result = new SendMessageDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.users)) {
            data["Users"] = [];
            for (let item of this.users)
                data["Users"].push(item);
        }
        data["Content"] = this.content;
        data["Title"] = this.title;
        data["Description"] = this.description;
        data["Url"] = this.url;
        data["MsgType"] = this.msgType;
        return data;
    }
}

export interface ISendMessageDto {
    users?: string[] | undefined;
    content?: string | undefined;
    title?: string | undefined;
    description?: string | undefined;
    url?: string | undefined;
    msgType?: WechatWorkMessageType;
}

export enum WechatWorkMessageType {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5,
}

export class WorkOrderSalesControl implements IWorkOrderSalesControl {
    编号?: string | undefined;
    用户编号?: string | undefined;
    用户铭?: string | undefined;
    修改状态?: string | undefined;
    创建时间?: string | undefined;
    锁定用户?: string | undefined;
    审核过程?: string | undefined;
    打印?: string | undefined;
    车间名称?: string | undefined;
    商品属性?: string | undefined;
    货号?: string | undefined;
    品名?: string | undefined;
    规格?: string | undefined;
    工单总数?: string | undefined;
    已入库数?: string | undefined;
    在产数量?: string | undefined;
    齐套?: string | undefined;
    配料?: string | undefined;
    分析日期?: string | undefined;
    生产完成率?: string | undefined;
    交货计划?: string | undefined;

    constructor(data?: IWorkOrderSalesControl) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.编号 = _data["编号"];
            this.用户编号 = _data["用户编号"];
            this.用户铭 = _data["用户铭"];
            this.修改状态 = _data["修改状态"];
            this.创建时间 = _data["创建时间"];
            this.锁定用户 = _data["锁定用户"];
            this.审核过程 = _data["审核过程"];
            this.打印 = _data["打印"];
            this.车间名称 = _data["车间名称"];
            this.商品属性 = _data["商品属性"];
            this.货号 = _data["货号"];
            this.品名 = _data["品名"];
            this.规格 = _data["规格"];
            this.工单总数 = _data["工单总数"];
            this.已入库数 = _data["已入库数"];
            this.在产数量 = _data["在产数量"];
            this.齐套 = _data["齐套"];
            this.配料 = _data["配料"];
            this.分析日期 = _data["分析日期"];
            this.生产完成率 = _data["生产完成率"];
            this.交货计划 = _data["交货计划"];
        }
    }

    static fromJS(data: any): WorkOrderSalesControl {
        data = typeof data === 'object' ? data : {};
        let result = new WorkOrderSalesControl();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["编号"] = this.编号;
        data["用户编号"] = this.用户编号;
        data["用户铭"] = this.用户铭;
        data["修改状态"] = this.修改状态;
        data["创建时间"] = this.创建时间;
        data["锁定用户"] = this.锁定用户;
        data["审核过程"] = this.审核过程;
        data["打印"] = this.打印;
        data["车间名称"] = this.车间名称;
        data["商品属性"] = this.商品属性;
        data["货号"] = this.货号;
        data["品名"] = this.品名;
        data["规格"] = this.规格;
        data["工单总数"] = this.工单总数;
        data["已入库数"] = this.已入库数;
        data["在产数量"] = this.在产数量;
        data["齐套"] = this.齐套;
        data["配料"] = this.配料;
        data["分析日期"] = this.分析日期;
        data["生产完成率"] = this.生产完成率;
        data["交货计划"] = this.交货计划;
        return data;
    }
}

export interface IWorkOrderSalesControl {
    编号?: string | undefined;
    用户编号?: string | undefined;
    用户铭?: string | undefined;
    修改状态?: string | undefined;
    创建时间?: string | undefined;
    锁定用户?: string | undefined;
    审核过程?: string | undefined;
    打印?: string | undefined;
    车间名称?: string | undefined;
    商品属性?: string | undefined;
    货号?: string | undefined;
    品名?: string | undefined;
    规格?: string | undefined;
    工单总数?: string | undefined;
    已入库数?: string | undefined;
    在产数量?: string | undefined;
    齐套?: string | undefined;
    配料?: string | undefined;
    分析日期?: string | undefined;
    生产完成率?: string | undefined;
    交货计划?: string | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}